from __future__ import annotations

import io
import json
import zipfile
from html import escape

import pandas as pd

from biosift.models import ColumnMapping, StudyDesign, ValidationIssue


def _generate_transformations_py(mappings: list[ColumnMapping]) -> str:
    rename_map = {
        mapping.source_column: mapping.standard_field
        for mapping in mappings
        if mapping.standard_field != "unknown"
    }

    lines = [
        '"""Reproducible transformations generated by BioSift."""',
        "",
        "import pandas as pd",
        "",
        'df = pd.read_csv("metadata.csv")',
        "",
        f"df = df.rename(columns={rename_map!r})",
        "",
    ]

    for mapping in mappings:
        if mapping.standard_field == "unknown" or not mapping.normalized_values:
            continue
        lines.extend(
            [
                f"df[{mapping.standard_field!r}] = df[{mapping.standard_field!r}].replace({mapping.normalized_values!r})",
                "",
            ]
        )

    lines.extend(
        [
            'df.to_csv("clean_metadata.csv", index=False)',
            'print("Wrote clean_metadata.csv")',
            "",
        ]
    )
    return "\n".join(lines)


def _quality_report_html(issues: list[ValidationIssue]) -> str:
    sections = []
    for issue in issues:
        evidence = "".join(f"<li>{escape(item)}</li>" for item in issue.evidence)
        sections.append(
            f"""
            <section class="issue {escape(issue.severity)}">
              <h2>{escape(issue.title)}</h2>
              <p><strong>Severity:</strong> {escape(issue.severity.upper())}</p>
              <p>{escape(issue.description)}</p>
              <p><strong>Recommendation:</strong> {escape(issue.recommendation)}</p>
              <ul>{evidence}</ul>
            </section>
            """
        )

    return f"""
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>BioSift Quality Report</title>
<style>
body {{ font-family: Arial, sans-serif; max-width: 900px; margin: 40px auto; color: #18202a; }}
h1 {{ margin-bottom: 4px; }}
.issue {{ border: 1px solid #d8dee8; border-left-width: 6px; border-radius: 10px; padding: 18px; margin: 18px 0; }}
.critical {{ border-left-color: #c62828; }}
.warning {{ border-left-color: #ef6c00; }}
.info {{ border-left-color: #1565c0; }}
</style>
</head>
<body>
<h1>BioSift Quality Report</h1>
<p>{len(issues)} issue(s) detected.</p>
{''.join(sections) if sections else '<p>No issues detected by the current validators.</p>'}
</body>
</html>
""".strip()


def build_export_zip(
    original_df: pd.DataFrame,
    cleaned_df: pd.DataFrame,
    mappings: list[ColumnMapping],
    study_design: StudyDesign,
    issues: list[ValidationIssue],
) -> bytes:
    buffer = io.BytesIO()

    data_dictionary = [
        {
            "source_column": mapping.source_column,
            "standard_field": mapping.standard_field,
            "confidence": mapping.confidence,
            "confidence_components": mapping.confidence_components,
            "reasoning_summary": mapping.reasoning_summary,
            "evidence": mapping.evidence,
            "normalized_values": mapping.normalized_values,
            "needs_review": mapping.needs_review,
        }
        for mapping in mappings
    ]

    config_lines = [
        "project: biosift_export",
        "version: 1",
        "inputs:",
        "  metadata: metadata.csv",
        "outputs:",
        "  clean_metadata: clean_metadata.csv",
        "  quality_report: quality_report.html",
        "  data_dictionary: data_dictionary.json",
        "review_required: true",
    ]

    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("metadata.csv", original_df.to_csv(index=False))
        archive.writestr("clean_metadata.csv", cleaned_df.to_csv(index=False))
        archive.writestr("data_dictionary.json", json.dumps(data_dictionary, indent=2, ensure_ascii=False))
        archive.writestr("study_design.json", study_design.model_dump_json(indent=2))
        archive.writestr("quality_report.html", _quality_report_html(issues))
        archive.writestr("transformations.py", _generate_transformations_py(mappings))
        archive.writestr("analysis_config.yaml", "\n".join(config_lines))

    return buffer.getvalue()
